### ISSUE TITLE
Automate updates 

### ISSUE THREAD

**Issue by genehack** [nextstrain/seasonal-cov#14]
(blocked by #13 , ~#12~ )

Write GitHub Actions to automatically run ingest step, check for new sequences, update phylogenetic output when new sequences are found.

**Comment by joverlee521** [comment]
References for this work

- [docs in pathogen-repo-guide](https://github.com/nextstrain/pathogen-repo-guide/blob/main/docs/nextstrain-internal/automated-pathogen-workflows.md)
- [Example GH Action workflow in zika](https://github.com/nextstrain/zika/blob/main/.github/workflows/ingest-to-phylogenetic.yaml)
