### ISSUE TITLE
Finalize datasets 

### ISSUE THREAD

**Issue by genehack** [nextstrain/seasonal-cov#20]
[Slack context](https://bedfordlab.slack.com/archives/C05BHL613AS/p1718394057776059)

- [x] drop host as coloring, all four of these are restricted to humans
- [x] drop host from list of filters
- [x] add country to list of filters
- [x] update byline with link to https://github.com/nextstrain/seasonal-cov
- [x] swap to "Maintained by Katie Kistler, John SJ Anderson, and the Nextstrain team"
- [x] fix map panel (see below)
- [x] update titles from "Genetic diversity of Human NL63", etc... to "Genomic epidemiology of seasonal coronavirus NL63", etc...

### Map panel 

I'm not quite sure why these are missing the map panel, I see it listed in the Auspice config under panels. I think maybe you just need to include geo_resolutions with [country listed](https://github.com/nextstrain/zika/blob/main/phylogenetic/defaults/auspice_config.json#L45)?

**Comment by jameshadfield** [comment]
> I think maybe you just need to include geo_resolutions

On the Augur side that should be enough. For Auspice, the dataset JSON needs ["map" in panels](https://github.com/nextstrain/augur/blob/0eab3357376f0fe7347fe60dd75dbc2fb01bed33/augur/data/schema-export-v2.json#L46-L47), a [geo_resolution](https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json#L52) with (at least some) deme to lat-long mappings, and some nodes on the tree must have values (e.g. you have to define country on at least one node!). If any of these Auspice requirements are invalid `augur export` _should_ warn you.

P.S. If you want transmission lines drawn on the map, then you'll need internal nodes of the tree to have properties defined (e.g. country to be defined). `augur traits` is how we usually do this, but I can't speak to the scientific validity of that in the context of this dataset.
